### ISSUE TITLE
Compatibility with Kafka 2.0

### ISSUE THREAD

**Issue by bacek** [kubeless/kafka-trigger#10]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug Report.

**What happened**:

Kafka Trigger isn't compatible with Kafka 2.0.

**What you expected to happen**:

Kafka Trigger process events from Kafka 2.0

**How to reproduce it (as minimally and precisely as possible)**:

Deploy kafka 2.0+ (e.g using strimzy 0.7+).
Configure kafka-trigger to use it. 
Deploy test kubeless function.
Connect it to kafka topic.

**Anything else we need to know?**:

After installing strimzy:0.7 and connecting kafka-trigger to it I've got that message in logs:

time="2018-10-22T05:54:17Z" level=error msg="Error: kafka: error while consuming ground-toolbox-k8s-events.json/0: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876\n"

(Every 2 seconds to be precise).

Main problem is described at https://github.com/Shopify/sarama/pull/1149 and was fixed in latest version of sarama (1.19.0). But kafka-trigger is locked 1.14.0

**Environment**:
- Kubernetes version (use `kubectl version`):
oc v3.10.34
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

- Kubeless version (use `kubeless version`):
Kubeless version: v1.0.0-alpha.8

- Cloud provider or physical cluster:
AWS

**Comment by andresmgot** [comment]
Hi all,

We have released a new version of the image (`v1.0.0`) that fix this issue. Please try it out and reopen this issue if you still find issues:

https://github.com/kubeless/kafka-trigger/releases/tag/v1.0.0
