### ISSUE TITLE
Get topic from inside handler_function

### ISSUE THREAD

**Issue by lunarray** [kubeless/kafka-trigger#21]
FEATURE REQUEST:

What happened:
Currently inside the kubeless handler function triggered by kafka trigger, we got two argument passed which is event and context. Inside both event and context there is no way to know what topic fired this event.

What you expected to happen:
There is a way to get the subscribed topic name passed to either context or event. Like maybe:

```
def forward(event, context):
  topic_name = context['kafka']['topic']
```

Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

```

- Kubeless version (use `kubeless version`)
Kubeless version: v1.0.4-dirty

- Cloud provider or physical cluster:
Self-managed kubernetes AWS

**Comment by jon-whit** [comment]
@andresmgot I put up a merge request to add this support. I'm happy to talk through alternatives, but for now I've extended the request headers to include the `event-topic` which triggered a given function. This will address this requested functionality, and my team also has an immediate need for this in our platform.

**Comment by andresmgot** [comment]
I've released https://github.com/kubeless/kafka-trigger/releases/tag/v1.0.4 with this, thanks!

**Comment by jon-whit** [comment]
@andresmgot awesome! Thank you.

**Comment by jon-whit** [comment]
@lunarray so you should now be able to access the `event-topic` like so:

```
def forward(event, context):
  topic = event['extensions']['request'].get_header('event-topic')
```
