### ISSUE TITLE
v1.0.3 Release

### ISSUE THREAD

**Issue by jon-whit** [kubeless/kafka-trigger#28]
@andresmgot mind releasing a `v1.0.3` release that includes the recent commits which patch the `KAFKA_BROKERS` #8 issue? That way we (clients) can point our Kubernetes release manifests against a stable tag.

**Comment by andresmgot** [comment]
yes, will do that today, thanks for the heads up

**Comment by andresmgot** [comment]
done! https://github.com/kubeless/kafka-trigger/releases/tag/v1.0.3

**Comment by jon-whit** [comment]
Thanks @andresmgot
