### ISSUE TITLE
KAFKA_BROKERS string is not correctly split to broker list (slice)

### ISSUE THREAD

**Issue by jsnowacki** [kubeless/kafka-trigger#8]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Following the external Kafka setup, if many brokers are added to `KAFKA_BROKERS` e.g.:

```bash
KAFKA_BROKERS=broker1:9092,broker2:9092
```

the variable is not split into `brokersSlice` as it should but passed as-is to consumer constructor, which causes connection error, as it tries to use the whole content of `KAFKA_BROKERS` as broker address.

**What you expected to happen**:
 `KAFKA_BROKERS` is split by comma and create list of brokers for consumer constructor.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
I have a fix on my fork and can submit a PR, but I am unable at the moment to run tests as the enviroment setup desctiption does not exist (https://github.com/kubeless/kafka-trigger/blob/master/docs/dev-guide.md) and manifest files in `libtest.bash` seem to be missing. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubeless version (use `kubeless version`):
```
Kubeless version: v1.0.0-alpha.7
```

- Cloud provider or physical cluster: physical cluster

**Comment by jsnowacki** [comment]
BTW fork branch https://github.com/jsnowacki/kafka-trigger/tree/kafka_brokers_fix

**Comment by rkelly-lg** [comment]
What is the hold-up for this fix? I would expect most production-grade deployments to utilize multiple brokers...

**Comment by andresmgot** [comment]
@jsnowacki would you mind creating a PR with the fix?

**Comment by jon-whit** [comment]
@andresmgot I submitted a PR for the fix. I'd like to get this in ASAP, because we are in need of it for a production grade use case with 3 Kafka brokers.

It looks like the build is failing, but due to reasons not related to the changes.

```
Error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```
